// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SerializationTestClass.proto

package proto.serializers;

public final class SerializationTestClassOuterClass {
  private SerializationTestClassOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SerializationTestClassOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SerializationTestClass)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * required
     * </pre>
     *
     * <code>optional string words = 1;</code>
     */
    java.lang.String getWords();
    /**
     * <pre>
     * required
     * </pre>
     *
     * <code>optional string words = 1;</code>
     */
    com.google.protobuf.ByteString
        getWordsBytes();

    /**
     * <code>repeated string list = 2;</code>
     */
    java.util.List<java.lang.String>
        getListList();
    /**
     * <code>repeated string list = 2;</code>
     */
    int getListCount();
    /**
     * <code>repeated string list = 2;</code>
     */
    java.lang.String getList(int index);
    /**
     * <code>repeated string list = 2;</code>
     */
    com.google.protobuf.ByteString
        getListBytes(int index);

    /**
     * <code>map&lt;string, int32&gt; map = 3;</code>
     */
    int getMapCount();
    /**
     * <code>map&lt;string, int32&gt; map = 3;</code>
     */
    boolean containsMap(
        java.lang.String key);
    /**
     * Use {@link #getMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Integer>
    getMap();
    /**
     * <code>map&lt;string, int32&gt; map = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.Integer>
    getMapMap();
    /**
     * <code>map&lt;string, int32&gt; map = 3;</code>
     */

    int getMapOrDefault(
        java.lang.String key,
        int defaultValue);
    /**
     * <code>map&lt;string, int32&gt; map = 3;</code>
     */

    int getMapOrThrow(
        java.lang.String key);

    /**
     * <pre>
     * required
     * </pre>
     *
     * <code>optional int32 integer = 4;</code>
     */
    int getInteger();

    /**
     * <pre>
     * required
     * </pre>
     *
     * <code>optional float floatNumber = 5;</code>
     */
    float getFloatNumber();
  }
  /**
   * Protobuf type {@code SerializationTestClass}
   */
  public  static final class SerializationTestClass extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SerializationTestClass)
      SerializationTestClassOrBuilder {
    // Use SerializationTestClass.newBuilder() to construct.
    private SerializationTestClass(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SerializationTestClass() {
      words_ = "";
      list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      integer_ = 0;
      floatNumber_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SerializationTestClass(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              words_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                list_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              list_.add(s);
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                map_ = com.google.protobuf.MapField.newMapField(
                    MapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
              map = input.readMessage(
                  MapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              map_.getMutableMap().put(map.getKey(), map.getValue());
              break;
            }
            case 32: {

              integer_ = input.readInt32();
              break;
            }
            case 45: {

              floatNumber_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          list_ = list_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.serializers.SerializationTestClassOuterClass.internal_static_SerializationTestClass_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.serializers.SerializationTestClassOuterClass.internal_static_SerializationTestClass_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.serializers.SerializationTestClassOuterClass.SerializationTestClass.class, proto.serializers.SerializationTestClassOuterClass.SerializationTestClass.Builder.class);
    }

    private int bitField0_;
    public static final int WORDS_FIELD_NUMBER = 1;
    private volatile java.lang.Object words_;
    /**
     * <pre>
     * required
     * </pre>
     *
     * <code>optional string words = 1;</code>
     */
    public java.lang.String getWords() {
      java.lang.Object ref = words_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        words_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * required
     * </pre>
     *
     * <code>optional string words = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWordsBytes() {
      java.lang.Object ref = words_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        words_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LIST_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList list_;
    /**
     * <code>repeated string list = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getListList() {
      return list_;
    }
    /**
     * <code>repeated string list = 2;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated string list = 2;</code>
     */
    public java.lang.String getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated string list = 2;</code>
     */
    public com.google.protobuf.ByteString
        getListBytes(int index) {
      return list_.getByteString(index);
    }

    public static final int MAP_FIELD_NUMBER = 3;
    private static final class MapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Integer>newDefaultInstance(
                  proto.serializers.SerializationTestClassOuterClass.internal_static_SerializationTestClass_MapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> map_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetMap() {
      if (map_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      return map_;
    }

    public int getMapCount() {
      return internalGetMap().getMap().size();
    }
    /**
     * <code>map&lt;string, int32&gt; map = 3;</code>
     */

    public boolean containsMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getMap() {
      return getMapMap();
    }
    /**
     * <code>map&lt;string, int32&gt; map = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Integer> getMapMap() {
      return internalGetMap().getMap();
    }
    /**
     * <code>map&lt;string, int32&gt; map = 3;</code>
     */

    public int getMapOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int32&gt; map = 3;</code>
     */

    public int getMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int INTEGER_FIELD_NUMBER = 4;
    private int integer_;
    /**
     * <pre>
     * required
     * </pre>
     *
     * <code>optional int32 integer = 4;</code>
     */
    public int getInteger() {
      return integer_;
    }

    public static final int FLOATNUMBER_FIELD_NUMBER = 5;
    private float floatNumber_;
    /**
     * <pre>
     * required
     * </pre>
     *
     * <code>optional float floatNumber = 5;</code>
     */
    public float getFloatNumber() {
      return floatNumber_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWordsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, words_);
      }
      for (int i = 0; i < list_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, list_.getRaw(i));
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
           : internalGetMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
        map = MapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(3, map);
      }
      if (integer_ != 0) {
        output.writeInt32(4, integer_);
      }
      if (floatNumber_ != 0F) {
        output.writeFloat(5, floatNumber_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWordsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, words_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < list_.size(); i++) {
          dataSize += computeStringSizeNoTag(list_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getListList().size();
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
           : internalGetMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
        map = MapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, map);
      }
      if (integer_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, integer_);
      }
      if (floatNumber_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, floatNumber_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.serializers.SerializationTestClassOuterClass.SerializationTestClass)) {
        return super.equals(obj);
      }
      proto.serializers.SerializationTestClassOuterClass.SerializationTestClass other = (proto.serializers.SerializationTestClassOuterClass.SerializationTestClass) obj;

      boolean result = true;
      result = result && getWords()
          .equals(other.getWords());
      result = result && getListList()
          .equals(other.getListList());
      result = result && internalGetMap().equals(
          other.internalGetMap());
      result = result && (getInteger()
          == other.getInteger());
      result = result && (
          java.lang.Float.floatToIntBits(getFloatNumber())
          == java.lang.Float.floatToIntBits(
              other.getFloatNumber()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + WORDS_FIELD_NUMBER;
      hash = (53 * hash) + getWords().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      if (!internalGetMap().getMap().isEmpty()) {
        hash = (37 * hash) + MAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMap().hashCode();
      }
      hash = (37 * hash) + INTEGER_FIELD_NUMBER;
      hash = (53 * hash) + getInteger();
      hash = (37 * hash) + FLOATNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getFloatNumber());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.serializers.SerializationTestClassOuterClass.SerializationTestClass parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.serializers.SerializationTestClassOuterClass.SerializationTestClass parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.serializers.SerializationTestClassOuterClass.SerializationTestClass parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.serializers.SerializationTestClassOuterClass.SerializationTestClass parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.serializers.SerializationTestClassOuterClass.SerializationTestClass parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.serializers.SerializationTestClassOuterClass.SerializationTestClass parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.serializers.SerializationTestClassOuterClass.SerializationTestClass parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.serializers.SerializationTestClassOuterClass.SerializationTestClass parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.serializers.SerializationTestClassOuterClass.SerializationTestClass parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.serializers.SerializationTestClassOuterClass.SerializationTestClass parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.serializers.SerializationTestClassOuterClass.SerializationTestClass prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SerializationTestClass}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SerializationTestClass)
        proto.serializers.SerializationTestClassOuterClass.SerializationTestClassOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.serializers.SerializationTestClassOuterClass.internal_static_SerializationTestClass_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.serializers.SerializationTestClassOuterClass.internal_static_SerializationTestClass_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.serializers.SerializationTestClassOuterClass.SerializationTestClass.class, proto.serializers.SerializationTestClassOuterClass.SerializationTestClass.Builder.class);
      }

      // Construct using proto.serializers.SerializationTestClassOuterClass.SerializationTestClass.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        words_ = "";

        list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableMap().clear();
        integer_ = 0;

        floatNumber_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.serializers.SerializationTestClassOuterClass.internal_static_SerializationTestClass_descriptor;
      }

      public proto.serializers.SerializationTestClassOuterClass.SerializationTestClass getDefaultInstanceForType() {
        return proto.serializers.SerializationTestClassOuterClass.SerializationTestClass.getDefaultInstance();
      }

      public proto.serializers.SerializationTestClassOuterClass.SerializationTestClass build() {
        proto.serializers.SerializationTestClassOuterClass.SerializationTestClass result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.serializers.SerializationTestClassOuterClass.SerializationTestClass buildPartial() {
        proto.serializers.SerializationTestClassOuterClass.SerializationTestClass result = new proto.serializers.SerializationTestClassOuterClass.SerializationTestClass(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.words_ = words_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          list_ = list_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.list_ = list_;
        result.map_ = internalGetMap();
        result.map_.makeImmutable();
        result.integer_ = integer_;
        result.floatNumber_ = floatNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.serializers.SerializationTestClassOuterClass.SerializationTestClass) {
          return mergeFrom((proto.serializers.SerializationTestClassOuterClass.SerializationTestClass)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.serializers.SerializationTestClassOuterClass.SerializationTestClass other) {
        if (other == proto.serializers.SerializationTestClassOuterClass.SerializationTestClass.getDefaultInstance()) return this;
        if (!other.getWords().isEmpty()) {
          words_ = other.words_;
          onChanged();
        }
        if (!other.list_.isEmpty()) {
          if (list_.isEmpty()) {
            list_ = other.list_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureListIsMutable();
            list_.addAll(other.list_);
          }
          onChanged();
        }
        internalGetMutableMap().mergeFrom(
            other.internalGetMap());
        if (other.getInteger() != 0) {
          setInteger(other.getInteger());
        }
        if (other.getFloatNumber() != 0F) {
          setFloatNumber(other.getFloatNumber());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.serializers.SerializationTestClassOuterClass.SerializationTestClass parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.serializers.SerializationTestClassOuterClass.SerializationTestClass) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object words_ = "";
      /**
       * <pre>
       * required
       * </pre>
       *
       * <code>optional string words = 1;</code>
       */
      public java.lang.String getWords() {
        java.lang.Object ref = words_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          words_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * required
       * </pre>
       *
       * <code>optional string words = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWordsBytes() {
        java.lang.Object ref = words_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          words_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * required
       * </pre>
       *
       * <code>optional string words = 1;</code>
       */
      public Builder setWords(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        words_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * required
       * </pre>
       *
       * <code>optional string words = 1;</code>
       */
      public Builder clearWords() {
        
        words_ = getDefaultInstance().getWords();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * required
       * </pre>
       *
       * <code>optional string words = 1;</code>
       */
      public Builder setWordsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        words_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          list_ = new com.google.protobuf.LazyStringArrayList(list_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string list = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getListList() {
        return list_.getUnmodifiableView();
      }
      /**
       * <code>repeated string list = 2;</code>
       */
      public int getListCount() {
        return list_.size();
      }
      /**
       * <code>repeated string list = 2;</code>
       */
      public java.lang.String getList(int index) {
        return list_.get(index);
      }
      /**
       * <code>repeated string list = 2;</code>
       */
      public com.google.protobuf.ByteString
          getListBytes(int index) {
        return list_.getByteString(index);
      }
      /**
       * <code>repeated string list = 2;</code>
       */
      public Builder setList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 2;</code>
       */
      public Builder addList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 2;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<java.lang.String> values) {
        ensureListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, list_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 2;</code>
       */
      public Builder clearList() {
        list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 2;</code>
       */
      public Builder addListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureListIsMutable();
        list_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Integer> map_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetMap() {
        if (map_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MapDefaultEntryHolder.defaultEntry);
        }
        return map_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetMutableMap() {
        onChanged();;
        if (map_ == null) {
          map_ = com.google.protobuf.MapField.newMapField(
              MapDefaultEntryHolder.defaultEntry);
        }
        if (!map_.isMutable()) {
          map_ = map_.copy();
        }
        return map_;
      }

      public int getMapCount() {
        return internalGetMap().getMap().size();
      }
      /**
       * <code>map&lt;string, int32&gt; map = 3;</code>
       */

      public boolean containsMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer> getMap() {
        return getMapMap();
      }
      /**
       * <code>map&lt;string, int32&gt; map = 3;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Integer> getMapMap() {
        return internalGetMap().getMap();
      }
      /**
       * <code>map&lt;string, int32&gt; map = 3;</code>
       */

      public int getMapOrDefault(
          java.lang.String key,
          int defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, int32&gt; map = 3;</code>
       */

      public int getMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMap() {
        getMutableMap().clear();
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; map = 3;</code>
       */

      public Builder removeMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableMap().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer>
      getMutableMap() {
        return internalGetMutableMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, int32&gt; map = 3;</code>
       */
      public Builder putMap(
          java.lang.String key,
          int value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        getMutableMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; map = 3;</code>
       */

      public Builder putAllMap(
          java.util.Map<java.lang.String, java.lang.Integer> values) {
        getMutableMap().putAll(values);
        return this;
      }

      private int integer_ ;
      /**
       * <pre>
       * required
       * </pre>
       *
       * <code>optional int32 integer = 4;</code>
       */
      public int getInteger() {
        return integer_;
      }
      /**
       * <pre>
       * required
       * </pre>
       *
       * <code>optional int32 integer = 4;</code>
       */
      public Builder setInteger(int value) {
        
        integer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * required
       * </pre>
       *
       * <code>optional int32 integer = 4;</code>
       */
      public Builder clearInteger() {
        
        integer_ = 0;
        onChanged();
        return this;
      }

      private float floatNumber_ ;
      /**
       * <pre>
       * required
       * </pre>
       *
       * <code>optional float floatNumber = 5;</code>
       */
      public float getFloatNumber() {
        return floatNumber_;
      }
      /**
       * <pre>
       * required
       * </pre>
       *
       * <code>optional float floatNumber = 5;</code>
       */
      public Builder setFloatNumber(float value) {
        
        floatNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * required
       * </pre>
       *
       * <code>optional float floatNumber = 5;</code>
       */
      public Builder clearFloatNumber() {
        
        floatNumber_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SerializationTestClass)
    }

    // @@protoc_insertion_point(class_scope:SerializationTestClass)
    private static final proto.serializers.SerializationTestClassOuterClass.SerializationTestClass DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.serializers.SerializationTestClassOuterClass.SerializationTestClass();
    }

    public static proto.serializers.SerializationTestClassOuterClass.SerializationTestClass getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SerializationTestClass>
        PARSER = new com.google.protobuf.AbstractParser<SerializationTestClass>() {
      public SerializationTestClass parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SerializationTestClass(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SerializationTestClass> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SerializationTestClass> getParserForType() {
      return PARSER;
    }

    public proto.serializers.SerializationTestClassOuterClass.SerializationTestClass getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SerializationTestClass_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SerializationTestClass_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SerializationTestClass_MapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SerializationTestClass_MapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034SerializationTestClass.proto\"\266\001\n\026Seria" +
      "lizationTestClass\022\r\n\005words\030\001 \001(\t\022\014\n\004list" +
      "\030\002 \003(\t\022-\n\003map\030\003 \003(\0132 .SerializationTestC" +
      "lass.MapEntry\022\017\n\007integer\030\004 \001(\005\022\023\n\013floatN" +
      "umber\030\005 \001(\002\032*\n\010MapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
      "value\030\002 \001(\005:\0028\001B\023\n\021proto.serializersb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SerializationTestClass_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SerializationTestClass_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SerializationTestClass_descriptor,
        new java.lang.String[] { "Words", "List", "Map", "Integer", "FloatNumber", });
    internal_static_SerializationTestClass_MapEntry_descriptor =
      internal_static_SerializationTestClass_descriptor.getNestedTypes().get(0);
    internal_static_SerializationTestClass_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SerializationTestClass_MapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
